"""Add student_id, theme, and notifications_enabled to UserProfile

Revision ID: 487abb9a6210
Revises: d398a8d40ce8
Create Date: 2026-08-15 13:03:08.989767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487abb9a6210'
down_revision: Union[str, Sequence[str], None] = 'd398a8d40ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('student_id', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('theme', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'notifications_enabled')
    op.drop_column('user_profiles', 'theme')
    op.drop_column('user_profiles', 'student_id')
    # ### end Alembic commands ###
